INSERT INTO UNIT (ID, NAME) VALUES (1, 'Unit1');
INSERT INTO UNIT (ID, NAME) VALUES (2, 'Unit2');
INSERT INTO PROJECT (ID, NAME) VALUES (1, 'Project1');
INSERT INTO PROJECT (ID, NAME) VALUES (2, 'Project2');
INSERT INTO PERSONAL_INFO (ID, NAME) VALUES (1, 'Ron');
INSERT INTO PERSONAL_INFO (ID, NAME) VALUES (2, 'Richard');
INSERT INTO EMPLOYEE (ID, CITY, STREET, HOUSE, APARTMENT, STATUS, UNIT_ID, PERSONAL_INFO_ID) VALUES (1, 'New York', '48th', '11a', '142', 'BILLABLE', 1, 1);
INSERT INTO EMPLOYEE (ID, CITY, STREET, HOUSE, APARTMENT, STATUS, UNIT_ID, PERSONAL_INFO_ID) VALUES (2, 'New York', '12th', '141', '1', 'NON_BILLABLE', 1, 2);